# Welcome to Jekyll!
#

# Site settings
title: "Regula Wolf"
slogan: "Stiftungs- und Public Management"
description: |
  Wirkungsorientiert fördern: Angebote für Stiftungen, private und
  öffentliche Förderorganisationen

owner: Regula Wolf
first_published: 2018
email: regula.wolf@gmx.ch
baseurl: ""
url: "http://regulawolf.ch"
social:
  twitter: https://twitter.com/RegulaWolf
  github: https://github.com/regulawolf
  linkedin-square: https://linkedin.com/in/regula-wolf-971b8657
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

jumbo: gaia tree kulturpolitik.jpg
